### ISSUE TITLE
Emit event on account creation and use it to build bundle and to send email

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#109]
- Define on models an event struct AccountCreated. It should contain at least the account_id and it's email
- Define an event handler for that event on the account domain that should send an email to the account's email (right now send an empty email)
- Define a flow (on the file `account/service/flow/account.ex`) that will:
  - Create an entity for the account
  - Create a server for the entity
  - Create basic hardware for the entity
  - Link all components on the motherboard
  - Attach the motherboard to the server
  - All those using their domains API
- Define another event handler for the account created event that will execute the above flow

Use as reference:
- `Software.Model.SoftwareType.Encryptor.ProcessConclusionEvent` for the event struct
- `HELF.Flow.on_{done,success,fail}/1` documentation for the Flow part
- `Software.Service.Event.Decryptor` for the event handler
- `Software.Service.Event.EncryptorTest` for the event handler test

To test the flow, just insert an account in the database, execute the flow and with the return, check on every API (probably using fetch functions) that the side-effect was achieved

**Comment by mememori** [comment]
The initial hardware bundle should be:

```elixir
%{
  motherboard: "MOBO01",
  components:  [
    {:cpu, "CPU01"},
    {:ram, "RAM01"},
    {:hdd, "HDD01"},
    {:nic, "NIC01"}
  ],
  network: [
    {"::", uplink: 100, downlink: 100}
  ]
}
```

**Comment by kress95** [comment]
I'll need to ask some things before continuing with this task (to avoid wasting time), but I'll come back to it asap.

**Comment by kress95** [comment]
I'll need some more guidance about this task, trying to implement it raised many doubts about the correct way of doing it, I'll try to ask everything on the correct order:

1. What to do if creating the entity fails? (`nothing | delete account`)
2. Where the ownership of `Entity` over `{server,components}` should be added? (`with clause | on_success`)
3. About the following domains:
  - Entity lacks: `create / delete` functions
  - Server lacks a `delete` function
  - Account lacks a `delete` function (only needed if `1. -> delete account`)
  > I have a commit here adding them, but I don't know if it's okay to send it on this PR
4. The bundle creation process looks something to be fully done on `Hardware API` with a transaction, but I don't know what's the best place to do it (Flow / API / Model / Controller)
5. I'm using `create_from_spec` a lot, it means that every time this flow happens the database has to fetch the same data over and over again (I don't think a cache should be added now, I'm just mentioning)

While the task is so simple to explain, the many (bad/good) ways to do it and the lack of experience to know which method is the best is causing me so much anxiousness :disappointed:
