### ISSUE TITLE
Software File Controller's `get_files_on_target_storage` is not returning encrypted files

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#130]
As a lapse of reason, i implemented the fetching of files on a software as if encryted files were actually hidden.

To fix that:

1) Remove on that function the code that filters files on the storage by their `crypto_version` being nil
2) Move the part that get the file_ids for which you have a valid key to another function (as i think it might be better for the client to ask 2 requests; one for the files and another to know which of these albeit being encrypted the user can still use)

**Comment by kress95** [comment]
closed by #142
