### ISSUE TITLE
Update HELL.PK to include timestamp information

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#144]
Right now the generated PK is an IPv6 that includes 42bits of metadata and 80bits of random strongly generated bits. So it's format is right now `"xxxx:xxxx:xxxx:yyyy:yyyy:yyyy:yyyy:yyyy"` being `x` metadata about which "thing" the object belongs to and `y` the random bits.

42bits of space to tell what the thing is is a bit too much actually as it allows over 4 trillion different values.

This issue intends to include Unix timestamp (32 bits of data) to the generated PK and reduce the metadata space to 16bits (allowing effectively over 65k different combinations).

That would make the pk format become `"zzzz:zzzz:yyyy:yyyy:yyyy:yyyy:yyyy:xxxx"` (with `z` being timestamp, `y` being random bits and `x` being metadata) this would make it easy to compare two IDs as you could simply compare them as strings and the "larger" one is the one that is more recent. It also allows us to easily recognize the kind of object the ID belongs to by checking the last 4 digits.

Finally, by having the unix timestamp (and by having it as the first part of the id) we can easily filter data by date and that would allow us to make efficient pagination on things like the `logs` entity.

Since this change would still leave the pk with 80bits of random strongly generated bits and 32bits of time-based bits, we have room to include more metadata (i'd go as far as to say that we don't need more than 48 bits of random strongly generated bits to accompany the 32bits of timestamp to ensure we are safe from collisions, so that would give us 48bits of potential space for extra meta information).

I think this is a good decision but i'd like your opinion, @renatomassaro

**Comment by renatomassaro** [comment]
Superseded by #377
