### ISSUE TITLE
Tag all tests to allow us to run only suites that makes sense at a context

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#15]
Use the following tags (some tests can have more than one tag):

```elixir
:unit # A test that requires only a single node and doesn't depend on any third-party software, only the Erlang environment
:integration # A test that depends on a third-party application and side-effects
:fullstack # A test that depends on a third-party application that is not the main rdbms (postgres)
:external # A test that depends on a third-party application that is accessible only through the internet
:cluster # A test that depends on more than a single erlang node
```

**Comment by kress95** [comment]
I'll not update service tests (we all know they're deprecated).
Is moduletag usage allowed?

**Comment by kress95** [comment]
From my understanding, model tests are usually unitary tests, except when using the `Repo`, right?

**Comment by mememori** [comment]
Model tests should be always unitary as models should not cause any side-effect

`@moduletag` usage is incentivized

**Comment by kress95** [comment]
I'm not sure if `Helix.Process.Controller.TableOfProcesses.Allocator.PlanTest` is `:integration` or `:unit` :unamused:

**Comment by mememori** [comment]
if the test causes side-effects it's integ, unit otherwise
