### ISSUE TITLE
Provide functionality to get all connections from node A to B

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#171]
Basically, fetch all connections whose tunnel has input gateway and input endpoint.

Possible interface:
```elixir
get_connections_tunneling_through(HELL.PK.t, HELL.PK.t) :: [Connection.t]

get_connection_ids_tunneling_through(HELL.PK.t, HELL.PK.t) :: [HELL.PK.t]

get_connection_types_tunneling_through(HELL.PK.t, HELL.PK.t) :: [HELL.Constant.t]
```

Note that `get_connection_types_tunneling_through/2` returns a set (ie: each result is unique)

**Places to fix on this change:**
- Henforcer.Network

**Comment by renatomassaro** [comment]
Implemented with `get_hops/1` and `get_links/1` on `NetworkQuery`.
