### ISSUE TITLE
Centralize Henforcer

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#172]
Put Henforcer into a centralized point on the application and give it a supervison tree.

Henforcer will not only provide methods to check certain rules but also keep a local state for every session for the user.

That way we can centralize the check mechanics so it is compatible with both websockets and http (without risk of different behaviour on any)

`service/api` of a domain's would no longer apply any Henforcer check. Instead a `service/public` would be implemented. It would receive two params: 1) a struct representing an instance of henforcer and 2) the params as a map. It would then proceed to use the henforcer instance to validate if the action is allowed.

That would vaguely mean
- Websocket connection is started
- Henforcer instance is started
- User asks to connect to "server:123" (ie: receive it's notifications and do actions on it's context)
- Websocket try to initiate a channel
- Channel asks henforcer to check if user has connection to server "123"
- Henforcer does a lot of checks
- Henforcer returns a boolean telling the websocket that there is a connection (on the case of connection between two servers, after being checked once, it'll be cached on the henforcer instance)
- User is allowed to join channel "server:123"
- User asks on that channel to get the files on a server
- Channel tries to execute "get_files" action on File Public API, passing the henforcer instance as a parameter, and on the other parameter, the additional data (gateway and destination)
- Public API calls the henforcer asking if there is a valid connection between both nodes (and as it's cached on henforcer, the response is an immediate yes)
- Public API executes Internal API get_files function
- Channel responds the request with the files

**Comment by renatomassaro** [comment]
Invalidated by new Henforcer format
