### ISSUE TITLE
Server Channel - Allow the user to connect to their own server using another gateway

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#191]
As it is now, the server channel uses the destination server as the topic. Supposing that the client keeps the channels open all the time for the player's own gateways, they would not be able to connect from a different gateway into one of their own servers.

Related to this issue, the player can't connect to the same destination server using different gateways for that very reason (ie: both connections would use the same topic)

Note that this is an issue that can be solved on the client by simply closing all server related channels when the player changes the active gateway but it might be more interesting to provide support to open channels on a background connection

**Comment by renatomassaro** [comment]
Fixed on PR #273
