### ISSUE TITLE
TOP improvement - estimated process completion date

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/Helix#254]
Given process objective and current resource utilization, provide estimated process conclusion date.

**Comment by mememori** [comment]
It does already do this. But that field is not persisted. I think it's a function called `Model.Process.load_virtual_data/1`

**Comment by mememori** [comment]
Found the issue. `Process.Internal.fetch/1` wasn't applying the `load_virtual_data` function, so, if you used fetch, it would not include estimated conclusion.
