### ISSUE TITLE
Discuss best return format for process file_id

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/Helix#263]
Specially on partial processes, the client does not have access to the object with such `file_id`, in which case we have to send file name and version directly.

Also related is how to handle never-ending processes on the client model (some processes do not have known completion time, nor progress, and are thus always running). Bruteforce, LogForger, Overflow are some examples. Download/Upload/BankTransfer are examples of processes where the user knows the completion date beforehand.

@kress95

**Comment by kress95** [comment]
Wait, is File ID private even for full access?
If it's not, don't worry, I'm aware that it should be a Maybe (because not every process comes from a file).

I think that the best choice is moving the file id to the full access record, as a maybe.

**Comment by renatomassaro** [comment]
Superseded by #272
