### ISSUE TITLE
Update Log Controller to use the new find/fetch format

### ISSUE THREAD

**Issue by mememori** [HackerExperience/Helix#52]
```elixir
fetch(HELL.PK.t) :: Log.t | nil
find([{:server_id, HELL.PK.t} | {:crypto_version, non_neg_integer | nil} | {:message, String.t}, ...], meta :: []) :: [Log.t]
```

Note that `message` on find is a `LIKE` filter
also note that, to avoid potential bugs, ecto does not accept `where thing = ^var` if `var` is nil, you'd have to write `where is_nil(thing)`

**Comment by kress95** [comment]
Reasoning for changing task estimate: creating the methots is pretty simple, but I'll have to figure about the tests.
