### ISSUE TITLE
Implement mapping of storage_id to server

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/Helix#83]
We'll add caches through our application when it makes sense to reduce the effort to fetch a commonly used information. Right now, fetching all storage that belong to a server is quite expensive (Get server, get motherboard, find HDDs attached to motherboard, find storages attached to HDDs).

A solution is to add a cache mapping all storage_ids that belong to a single server. The primary key is the tuple (server_id, storage_id). storage_id is unique; server_id isn't.

Since both storage_id and servers won't change too often, and will be read all the time, it makes sense to create a materialized view that is updated through triggers (when new storage_ids are created/removed). Or we can simply create a new table. I don't think there is a difference at all in this case.

**Comment by mememori** [comment]
Moving this back to backlog based on my comment on #84

**Comment by mememori** [comment]
I think this was done on cache implementation PR, right ?
